### ISSUE TITLE
关于执行onDocumentClick问题

### ISSUE THREAD

**Issue by sundyxfan** [react-component/trigger#11]
场景是单击下拉框(trigger包装)，展示下拉列表(单击下拉列表收回下拉列表)，单击某项出现模态窗，然后单击任何地方，下拉框收回，理想的效果是触发模态窗的逻辑，因为先触犯trigger绑定的mousedown引起的，如何避免这种情况的发生？

**Comment by yiminghe** [comment]
need demo

**Comment by yiminghe** [comment]
closing
