### ISSUE TITLE
Include additional elements to trigger overlay area

### ISSUE THREAD

**Issue by aight8** [react-component/trigger#14]
I don't know exactly if this have something to do with the previous issue: https://github.com/react-component/trigger/issues/11

The problem is that when you use component's which render outside of the trigger popup component (best example is the rc-dropdown component) any event which is fired on this content (onClick, mouseLeave) will propagated to the onDocumentClick event which execute the code which close the popup after the configured time or instantly (in the case when clicking an item in the dropdown menu).

So my idea is to add an additional property to the trigger component (called something like includedPopupSelector). Which will be checked in the triggers onDocumentClick and onLeave event too (with the same logic likes jQueries closest method https://api.jquery.com/closest/#closest1)

Otherwise every other component which is based on rc-trigger and render something outside the popup can't be used.

Have you guys a better idea how to solve this cases?

**Comment by aight8** [comment]
https://github.com/react-component/trigger/pull/15

**Comment by yiminghe** [comment]
use controlled popupVisible
