### ISSUE TITLE
v4.3.1 breaks antd popover

### ISSUE THREAD

**Issue by e965** [react-component/trigger#189]
When I try to click on the button in popover trigger, the application crashes.

```js
    <Popover
        title={'test'}
        placement="bottomRight"
        trigger="click"
        content={
            <Form style={{ textAlign: 'center' }}>
                <Button onClick={console.log}>test</Button>
            </Form>
        }>
        <Button type="link" className="ant-btn--action" title={'test'}>
            test
        </Button>
    </Popover>
```

Console output at this moment:
![image](https://user-images.githubusercontent.com/18071040/88774289-af0a1b80-d19c-11ea-817a-ef3b26d39cc3.png)
![image](https://user-images.githubusercontent.com/18071040/88774301-b29da280-d19c-11ea-8b9b-cb27477a4af4.png)

**Comment by zombieJ** [comment]
https://github.com/react-component/trigger/releases/tag/v4.3.2
