### ISSUE TITLE
Module '"../node_modules/rc-trigger/lib/interface"' has no exported member 'MotionType'. Did you mean 'ActionType'?

### ISSUE THREAD

**Issue by maoxiaoke** [react-component/trigger#193]
问题：

node_modules/_rc-menu@8.3.1@rc-menu/es/interface.d.ts:2:30 - error TS2724: Module '"../node_modules/rc-trigger/lib/interface"' has no exported member 'MotionType'. Did you mean 'ActionType'?

问题描述：

1. rc-menu@8.3.1 依赖了 MotionType 但是最近的 rc-tigger@4.4.0 移除了对 MotionType 导致报错

**Comment by ReactLearningTrip** [comment]
解决了吗？

**Comment by guanyun-helo** [comment]
解决了吗？

**Comment by Kermit-Xuan** [comment]
最新的 rc-menu 也有问题么？

**Comment by guanyun-helo** [comment]
npm 就不会有这个问题，我在 json 里同级指定了 rc-trigger 的版本，yarn 会在 rc-menu 重新安装 rc-trigger 忽略举我的版本。

**Comment by Kermit-Xuan** [comment]
本地是不是有 yarn.lock 锁版本了？

**Comment by guanyun-helo** [comment]
没有，只有一个 package.json 。纯净的试验了 yarn 和 npm 两种安装方式，只有 yarn 会出现。
最新版没有试验，应为项目 ui 框架是锁版本的。

**Comment by Kermit-Xuan** [comment]
@zombieJ 应该是 rc-menu 安装的是 rc-trigger 的 4.x 最新版本，看能不能再发个 4.x 版本修复一下。

**Comment by zombieJ** [comment]
ts 定义里略过一下，minor 版本上不发 patch 了。否则分叉实在太多了。`@types/react` 也是不是来个不兼容的一定更新，antd 也是只保证最新的定义是对的。

**Comment by guanyun-helo** [comment]
好，只能这么做了
