### ISSUE TITLE
get popupInstance bug

### ISSUE THREAD

**Issue by eternalsky** [react-component/trigger#21]
https://github.com/react-component/trigger/blob/master/src/Trigger.jsx#L108
it seems unstable_renderSubtreeIntoContainer will tirgger it's callback before returning a component instance.
https://github.com/facebook/react/blob/d2ff462b79937ec3016dcba81d91d93a4a015c78/src/renderers/dom/client/ReactMount.js#L399

in Trigger, it will call props.afterPopupVisibleChange in the callback, and then dropdown's afterPopupVisibleChange will try to get the popupDomNode of trigger which is not returned and then cause an error.

**Comment by yiminghe** [comment]
https://github.com/react-component/trigger/commit/0cdfc92ec54b390f54abbf1314945bc644e8b2e5

**Comment by yiminghe** [comment]
https://github.com/react-component/trigger/commit/0cdfc92ec54b390f54abbf1314945bc644e8b2e5
