### ISSUE TITLE
Trigger does not work with a React component child

### ISSUE THREAD

**Issue by pdonias** [react-component/trigger#25]
Hi,
triggering a popup doesn't seem to work when the `Trigger`'s child is a React component.

So this works fine:

```js
import React, { Component } from 'react'
import Trigger from 'rc-trigger'

export default class MyPage extends Component {
  render () {
    return <Trigger
      action={['hover']}
      popup={<span>popup</span>}
      popupAlign={{
        points: ['tl', 'bl'],
        offset: [0, 3]
      }}
    >
      <span>This is my span</span>
    </Trigger>
  }
}
```

But this doesn't work (the "popup" message does not show when hovering `MyComponent`):

```js
import React, { Component } from 'react'
import Trigger from 'rc-trigger'

class MyComponent extends Component {
  render () {
    return <span>This is my component</span>
  }
}

export default class MyPage extends Component {
  render () {
    return <Trigger
      action={['hover']}
      popup={<span>popup</span>}
      popupAlign={{
        points: ['tl', 'bl'],
        offset: [0, 3]
      }}
    >
      <MyComponent />
    </Trigger>
  }
}
```

Is there a way I can make it work without wrapping the child with a span?
Thanks.

**Comment by julien-f** [comment]
I think you cannot use React handlers (e.g. `onClick`) with high level components, you should use [ReactDom.findDomNode](http://devdocs.io/react/docs/top-level-api#reactdom.finddomnode) and add the handler yourself.

**Comment by yiminghe** [comment]
````
<Trigger
      action={['hover']}
      popup={<span>popup</span>}
      popupAlign={{
        points: ['tl', 'bl'],
        offset: [0, 3]
      }}
    >
<span>
      <MyComponent />
</span>
    </Trigger>
````

**Comment by julien-f** [comment]
But one must know whether it's in a block or inline context (to know if a `<div>` or `<span>` should be used) and it introduced an intermediary which is not always possible (for instance with react-bootstrap's ButtonGroup).

**Comment by yiminghe** [comment]
span is always right

**Comment by antivanov** [comment]
Encountered the same issue. Looks like a bug/undocumented limitation in the implementation of the library.

There is an implicit assumption: the child component is expected to have event handler properties such as `onMouseLeave`, `onMouseEnter` which will be called correspondingly on mouse entering and leaving. This is the case with `div` and `span` but not with `MyComponent`.

One way to work around can be to add `onMouseEnter` and `onMouseLeave` properties to your component `MyComponent` which will have default values of an empty function. Then in the rendition of `MyComponent` make sure that `onMouseEnter` and `onMouseLeave` are called when mouse enters and leaves the child element.

For example

```javascript
class MyComponent {

  static defaultProps = {
    onMouseEnter: function() {},
    onMouseLeave: function() {}
  };
  ...
  render() {
     const props = {
         onMouseEnter: this.props.onMouseEnter,
         onMouseLeave: this.props.onMouseLeave
     };

    return <div {...props}></div>
  }
}
```

**Comment by antivanov** [comment]
Is it possible to, please, document this limitation of the current implementation in order to save time for people who encounter this issue?

Actually it should be even possible to fix this issue by adding some wrapper element around the child element (likely a `div` with some class name, please, note that `span` cannot have non-inline elements as children) and adding handlers to it instead of the child element.

**Comment by yiminghe** [comment]
welcome pr for docs.
this component is purely logic, I don't intend to add additional markup
