### ISSUE TITLE
Error: isMounted() not working with Components made with ES6 classes in React v14

### ISSUE THREAD

**Issue by mhodgson** [react-component/trigger#3]
This line uses a method that doesn't work when components are constructed as ES6 classes. I believe the problem I am having is just a scope issue. The references to `this` should really be references to `self`. 

https://github.com/react-component/trigger/blob/master/src/Trigger.jsx#L83

**Comment by yiminghe** [comment]
not related to es2015 class, you need to install the latest react(0.14.3)

**Comment by mhodgson** [comment]
@yiminghe thanks! Should the package.json requirements be updated or was this simply a bug in React?

**Comment by yiminghe** [comment]
a bug https://github.com/facebook/react/pull/5125
