### ISSUE TITLE
Popup jumps if content doesn't fit on one line

### ISSUE THREAD

**Issue by KatiRasanen** [react-component/trigger#30]
Hey,

I have a problem that on the first click/hover my popup aligns incorrectly, and on the second time it jumps on the correct place. The popup has long text inside and the text goes on two lines so that it fits in the window. With short texts the popup aligns correctly but if the window is scaled small and the text inside popup is even few words too long the jumping starts again.

I downloaded your project, added some long text on your simple example and got the same problem. So you can try that out aswell to see the issue. Do you have any idea where the misalignment might come from? I haven't found it yet.

**Comment by tailsu** [comment]
I'm also looking for a good solution to this. I patched the problem by disabling multi-line tooltips:

`<RcTooltip overlayStyle={{whiteSpace: 'nowrap'}}>....</RcTooltip>`

An actual solution would be very welcome.

**Comment by benjycui** [comment]
It seems that it is a problem in rc-algin, could you provide a re-producible demo? If you still meet this problem after upgrading to the latest version.

**Comment by benjycui** [comment]
Close for no response.
