### ISSUE TITLE
alwaysByViewport:boolean in dom-align

### ISSUE THREAD

**Issue by GabbereX** [react-component/trigger#306]
![image](https://user-images.githubusercontent.com/82294236/183103881-6b8a5db4-00d8-497f-8f3e-c636ee998e1d.png)
In dom-align package new option alwaysByViewport:boolean (https://github.com/yiminghe/dom-align). Please, add in interface  overflow:alwaysByViewport:boolean

**Comment by yoyo837** [comment]
Move to #414

**Comment by hasakilol** [comment]
could you elaborate? or could you give some hint on how to make a always stay in view port?
