### ISSUE TITLE
builtinPlacements and popupPlacement should be required props

### ISSUE THREAD

**Issue by michael8090** [react-component/trigger#31]
we get the following error without the two props:

![image](https://cloud.githubusercontent.com/assets/2306105/20509242/494a18fa-b0a2-11e6-9f90-2981897e0fb1.png)

**Comment by benjycui** [comment]
I don't understand, it seems that we had check these props exist or not before using them:

```jsx
if (popupPlacement && builtinPlacements) {
  className.push(getPopupClassNameFromAlign(builtinPlacements, prefixCls, align));
}
```

**Comment by benjycui** [comment]
If you still meet this problem, please PR, thanks.
