### ISSUE TITLE
Newest version 5.3.2 has issues, please take a look

### ISSUE THREAD

**Issue by stiles001** [react-component/trigger#312]
![image](https://user-images.githubusercontent.com/91835935/198064895-94bde446-2e25-4db8-94fb-ee0e5fba2ef1.png)

**Comment by stiles001** [comment]
@zombieJ

**Comment by digiz3d** [comment]
+1, just experiencing it now.
adding
```
  "resolutions": {
    "rc-trigger": "5.3.1"
  }
``` 
to our yarn.lock file solves the issue.

**Comment by MichaelBradetLegris** [comment]
+1 to digiz3d

**Comment by alexander-mh** [comment]
+1

**Comment by alexander-mh** [comment]
Same here 👀

**Comment by lille-etimo** [comment]
Just got bitten by this as well.

**Comment by omeraplak** [comment]
It will be released soon 💥

https://github.com/react-component/trigger/pull/314

**Comment by digiz3d** [comment]
Indeed, fix works; thanks for your reactivity ! 🚀
