### ISSUE TITLE
getComponent is undefined

### ISSUE THREAD

**Issue by yachaka** [react-component/trigger#34]
Using rc-select.
This is due to latest version change, but I can't figure out why you have green test on your last commit while it obviously doesn't pass.

**Comment by wolfadex** [comment]
This is also causing an issue with rc-tooltip.

**Comment by ineo6** [comment]
同样有getComponent问题.希望快点解决。

**Comment by benjycui** [comment]
Because you had imported different versions of rc-utils in your project.

`rm -rf node_modules && npm i`
