### ISSUE TITLE
Version 1.8 updated rc-util@4.x but rc-align already includes rc-util@3.x

### ISSUE THREAD

**Issue by timkindberg** [react-component/trigger#35]
Just like title states. By updating rc-util to 4.x you have introduced duplicate rc-util dependency, so now both versions are included in bundles. 

How about just remove rc-util from dependencies completely and just rely on transitive rc-util dep coming from rc-align?

**Comment by benjycui** [comment]
rc-trigger and rc-align rely on the same rc-util now.
