### ISSUE TITLE
@rc-component/trigger doesn't work with portals

### ISSUE THREAD

**Issue by Ke1sy** [react-component/trigger#434]
After update from v1.14.2 to  v1.14.3 I noticed that @rc-component/trigger doesn't work good with portals as previously.
We use the react-select with portal inside the antd Table filter dropdown (antd@5.6.3). Filter dropdown has the search value as well as "Filter" and "Clear" buttons. 
![image](https://github.com/react-component/trigger/assets/26119263/b0c9a10c-f8ad-49b1-bc8e-c75e04697cb6)

To apply the filter user should select option and type search value and click "Filter". But we faced the issues with select (react-select) that uses portals after @rc-component/trigger was updated to v1.14.3 or higher.

**Expected behaviour:**
After selecting the option, the dropdown is not closed and user can continue set up the filter.

Codesandbox with  v1.14.2:
https://codesandbox.io/s/filter-and-sorter-antd-5-10-0-forked-lygdxm?file=/demo.tsx

**Actual behaviour:**
After selecting the option, the dropdown is closed and user cannot continue set up the filter.

Codesandbox with  v1.14.3:
https://codesandbox.io/s/filter-and-sorter-antd-5-10-0-forked-q6h9s9?file=/demo.tsx

We believe that this issue is caused by these changes https://github.com/react-component/trigger/commit/854325fe8a25436f6ef127674c16e91f9deb3797.

CC: @mellis481

**Comment by mellis481** [comment]
@afc163 @zombieJ @MadCcc Can you please take a look at this issue and advise what you'd like to be done? To summarize, PR #412 (specifically the enabling of capture mode for the `mousedown` event handler - https://github.com/react-component/trigger/blob/master/src/hooks/useWinClick.ts#L33) has broken Ant Design `Table` instances using the `filterDropdown` prop when using portals.

**Comment by afc163** [comment]
@linxianxi Could you look into this one?

**Comment by Ke1sy** [comment]
JFYI we've found a workaround for our implementation.

**Comment by mellis481** [comment]
@linxianxi Can you please look at this issue?

**Comment by linxianxi** [comment]
I have not used react-select and do not understand how it is implemented.

**Comment by mellis481** [comment]
@linxianxi Did you have a chance to look at this problem?

**Comment by mellis481** [comment]
@afc163 What would you like to do with this issue? It doesn't seem like the person who created the PR that caused this regression is willing to address it.

> To summarize, PR https://github.com/react-component/trigger/pull/412 (specifically the enabling of capture mode for the mousedown event handler - https://github.com/react-component/trigger/blob/master/src/hooks/useWinClick.ts#L33) has broken Ant Design Table instances using the filterDropdown prop when using portals.

**Comment by linxianxi** [comment]
I think this behavior is expected
You can try mui, which is the same as antd https://codesandbox.io/p/sandbox/bold-fire-vgpqq7?file=%2Fsrc%2FDemo.tsx%3A50%2C16

**Comment by mellis481** [comment]
@linxianxi Can you please address @Ke1sy's comment?

**Comment by mellis481** [comment]
@afc163 What would you like to do with this issue? It doesn't seem like the person who created the PR that caused this regression is willing to address it.

**Comment by zombieJ** [comment]
`react-select` called [stopPropagation()](https://github.com/JedWatson/react-select/blob/28251dc5bac1fbb5863b5095f0ca94d7091926e1/packages/react-select/src/Select.tsx#L1284) to prevent outter get mouseDown event. So in prev version of trigger will be blocked by `react-select`.

For current version, to resolve the case when outer use `stopPropagation()` which makes trigger not get `mouseDown` event and can not close so it use capture to get the event. Which hit the way of `react-select` escape. Since the fix logic can not check `stopPropagation` is really want to not close, I guess it's not easy to fix.

**Comment by zombieJ** [comment]
`+ @rc-component/trigger@2.2.5`

https://codesandbox.io/p/sandbox/filter-and-sorter-antd-5-10-0-forked-m346tn?file=%2Fpackage.json%3A15%2C23
