### ISSUE TITLE
Global event handler option

### ISSUE THREAD

**Issue by sebfek** [react-component/trigger#5]
This component is very configurable, I like it. I miss a small additional functionality, what you think about it?:

Only one Popup visible at once even if you use the mouseLeaveDelay/blurDelay option. I have a special use case where you can hover over a bunch of tokens list. When your drag your mouse over a lot of tokens first before reach your target token and use the delay options, you have a lot of popups open at once before they disapper. A solution is to listen to a global 'popup-reset' event on the window object.

**edit:**
I made a quick wrapper arround the trigger component to show what I mean:
```JS
export default React.createClass({
    componentDidMount: function() {
        window.addEventListener('popup-visible', this.onWindowPopupVisible, false);
    },
    onWindowPopupVisible: function(event) {
        if (this.refs != null && this != event.detail.component) {
            return this.refs.baseTrigger.setState({
                popupVisible: false
            });
        }
    },
    componentWillUnmount: function() {
        window.removeEventListener('popup-visible', this.onWindowPopupVisible);
    },
    afterPopupVisibleChange: function(visible) {
        if (visible) {
            window.dispatchEvent(new CustomEvent('popup-visible', {detail: {component: this}}));
        }
    },
    render: function() {
        return (
            <BaseTrigger {...this.props}
                builtinPlacements={builtinPlacements}
                ref="baseTrigger"
                afterPopupVisibleChange={this.afterPopupVisibleChange} />
        );
    }
});
```

**Comment by yiminghe** [comment]
why not use mouseEnterDelay

**Comment by aight8** [comment]
I use it, but if the mouseLeveDelay is bigger then mouseEnterDelay then multiple popups appears. I want that the popup is longer visible unless another popup is opened. I must say it's a special use case

**Comment by yiminghe** [comment]
then you should use `popupVisible ` to have full control

**Comment by yiminghe** [comment]
closing. if has any question, reopen
