### ISSUE TITLE
problem of the new version 1.10.0

### ISSUE THREAD

**Issue by zhipengyan** [react-component/trigger#50]
在这个 [commit](https://github.com/react-component/trigger/commit/b9bb1608f12a852837416e9735b703601645cf94) 中，click 事件替代了 mousedown 事件，但是会引发一些问题，click 事件相对 mousedown 的事件响应顺序相对靠后，当在业务组件中通过点击 button-example（监听的是 click 事件）操作来更新了组件内容，在更新时如果 unmount 了一些内容且包含了 button-example，那么在 onDoumentClick 中判断是否执行的时候将会误伤，因为 document 的 click 事件监听触发时机较晚，button-example 可能已经不在容器中了。

感觉这种情况有点极端，我的使用场景是popover中点击按钮之后，需要更新popover中的内容。

**Comment by benjycui** [comment]
fixed in https://github.com/react-component/trigger/pull/52

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`
