### ISSUE TITLE
export 'findDOMNode' (imported as 'findDOMNode') was not found in 'react-dom'

### ISSUE THREAD

**Issue by dimple-pay2dc** [react-component/trigger#501]
After upgrading my react application to latest version, this lib throws error because it still uses findDOMNode

**Comment by JazzyGrim** [comment]
@dimple-pay2dc How did you resolve this?

**Comment by dimple-pay2dc** [comment]
> @dimple-pay2dc How did you resolve this?

Haven't resolved it yet. I am using rc-datepicker which still uses old react version and findDOMNode. I have opened an issue in their repo for the same
