### ISSUE TITLE
Probbably need to update overflown classname.

### ISSUE THREAD

**Issue by boba-keyost** [react-component/trigger#56]
If Popup has placement with overflow options, it changes className once to overflown, but does'nt switch back if overflownot needed.
E.G. : We have rc-select dropdown menu with 'bottomLeft' placement. If there is no place on screen popup className would be set to topLeft.

In onAlign function you only check if `alignClassName !== currentAlignClassName`, but I guess, you should also check if `this.currentAlignClassName !== currentAlignClassName`
``` 
onAlign = (popupDomNode, align) => {
    const props = this.props;
    const alignClassName = props.getClassNameFromAlign(props.align);
    const currentAlignClassName = props.getClassNameFromAlign(align);
    if (alignClassName !== currentAlignClassName) {
      this.currentAlignClassName = currentAlignClassName;
      popupDomNode.className = this.getClassName(currentAlignClassName);
    }
    props.onAlign(popupDomNode, align);
}
```

**Comment by benjycui** [comment]
ref: https://github.com/react-component/tooltip/issues/79

**Comment by benjycui** [comment]
1.11.2

**Comment by boba-keyost** [comment]
Ok, thanks!
