### ISSUE TITLE
How to stop trigger

### ISSUE THREAD

**Issue by relaxgo** [react-component/trigger#61]
Hey, thank you for the ant-design. It save me lots of time.

I have a problem when use Dropdown. I want do some check in child onClick event. if not valid, I want to stop show the dropdown.  But event.stopPropagation() doesn't work. should the [onClick](https://github.com/react-component/trigger/blob/master/src/index.js#L245) check the event is propagation stopped?  And I don't find any other way to stop show dropdown.

**Comment by benjycui** [comment]
`Dropdown[visible]` and `Dropdown[onVisibleChange]`
