### ISSUE TITLE
React.createElement: type is invalid for trigger used in rc-dropdown

### ISSUE THREAD

**Issue by corneyl** [react-component/trigger#62]
I'm using ant-design which utilises `rc-dropdown`. I get the following error for the type of `rc-trigger`, when `rc-dropdown` tries to create a React element of `rc-trigger`.
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Dropdown`.
    in Dropdown (created by Dropdown)
    in Dropdown (created by DashboardTemplate)
```
where the first dropdown is an `rc-dropdown` element, and the second one the dropdown element from `antd`. 

The code in `rc-dropdown` which yields the error:
```
return _react2["default"].createElement(
  _rcTrigger2["default"],
  _extends({}, otherProps, {
    prefixCls: prefixCls,
    ref: 'trigger',
    popupClassName: overlayClassName,
    popupStyle: overlayStyle,
    builtinPlacements: _placements2["default"],
    action: trigger,
    showAction: showAction,
    hideAction: hideAction,
    popupPlacement: placement,
    popupAlign: align,
    popupTransitionName: transitionName,
    popupAnimation: animation,
    popupVisible: this.state.visible,
    afterPopupVisibleChange: this.afterVisibleChange,
    popup: this.getMenuElement(),
    onPopupVisibleChange: this.onVisibleChange,
    getPopupContainer: getPopupContainer
  }),
  children
);
```
`_rcTrigger2` is defined as follows:
```
var _rcTrigger = require('rc-trigger');
var _rcTrigger2 = _interopRequireDefault(_rcTrigger);
```
I'm not totally sure whether it's a problem with `rc-trigger`, `rc-dropdown`, ant-design or e.g. Babel, but it is probably since the switch to ES code.

Any ideas?

**Comment by corneyl** [comment]
Ok, I got one step further. It seems that `_rcTrigger2` contains one extra level of 'default'. When I change `_rcTrigger2["default"]` to `_rcTrigger2["default"]["default"]`, it works. 
This is done by the function `_interopRequireDefault(obj) { ... }` which seems to be part of babel. Is this a problem in my babel config, or is the code in the npm package broken?

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by corneyl** [comment]
Well, the problem is that the codepen snippet doesn't use webpack, so it's not possible to reproduce there. I'll try to create a demo repository, but it can take a while because of holidays.

**Comment by benjycui** [comment]
Close for no response.

**Comment by corneyl** [comment]
FYI: I just figured out 3 days ago that updating babel-loader to 7.1.0 (from 6.21.x) solved this problem.
