### ISSUE TITLE
popup 位置错误

### ISSUE THREAD

**Issue by lpgray** [react-component/trigger#73]
[图片无法展现](http://ww1.sinaimg.cn/large/8df27f17gy1fl03mxh5qnj20w80fm75u.jpg)
> github图片抽风，点进去外链看即可

如上图，Modal 弹层里面有一个 Trigger，body 的高度很大，Popup 就会有一部分展现不出来，debug了一下代码，发现跟 dom-align 有关，domAlign 函数计算可显示区域的尺寸有问题，忽略了 body 为 overflow: hidden 的场景

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by lpgray** [comment]
@benjycui OK, 这是我的 demo: https://codepen.io/lpgray/pen/QOwNxZ

**Comment by benjycui** [comment]
看起来还好





![image](https://user-images.githubusercontent.com/3580607/32205792-5b8112a0-bdbf-11e7-9506-8e469e692a08.png)

**Comment by lpgray** [comment]
@benjycui 你把浏览器的高度变矮一点，刚好看不到 17 行以下那部分

**Comment by benjycui** [comment]
```diff
<Dropdown
+ getPopupContainer={(triggerNode) => triggerNode.parentNode}
/>
```

**Comment by lpgray** [comment]
@benjycui 其实你这个 case 解决的不彻底，应该任何时候都能够支持显示正确的位置，而不是必须设置到 parentNode 中

**Comment by eternalsky** [comment]
+1 ，如果要是需要区分环境设置在不同的 wrapper 里的话，总感觉不是一种很好的解决思路。如果是 align 的问题，最好从 align 的层面加以解决。
