### ISSUE TITLE
createPortal breaks usage from react 14 & 15

### ISSUE THREAD

**Issue by jooj123** [react-component/trigger#75]
Getting errors about `createPortal` not being defined for react 15

I think this import is the culprit:
https://github.com/react-component/trigger/blob/6e3c43735fb4a3352c6d22395fa977d8940f65a4/src/index.js#L3

Probably needs to be conditionally loaded instead?

**Comment by benjycui** [comment]
Please provide a re-producible demo.

**Comment by jsanchez034** [comment]
I ran into this issue as well with `rollup` build tool and using `rollup-plugin-commonjs`. The solution was to pass the `namedExports` configuration parameter to `rollup-plugin-commonjs`..
```
    commonjs({
      include      : 'node_modules/**',
      namedExports : { // remove this line when upgrading to React 16
        'react-dom' : [
          'createPortal',
          'findDOMNode',
          'render',
          'unmountComponentAtNode',
          'version',
          'unstable_batchedUpdates',
          'unstable_renderSubtreeIntoContainer'
        ]
      }
    }),
```
Note how I added `createPortal` in there. Once you are using React 16 you can remove the `namedExports` parameter.
