### ISSUE TITLE
建议不要写死create-react-class版本

### ISSUE THREAD

**Issue by liupeng110112** [react-component/trigger#79]
当使用antd组件（比如select组件）打包出来时再次使用的时候会抛出
`getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead`
这个警告

原因是在rc-trigger组件使用了老版本的create-react-class版本 ，创建出来的component 的getDefaultProps有个属性isReactClassApproved 为undefined ，react的这个方法validatePropTypes会检查抛出这个错误

**Comment by yesmeck** [comment]
已去掉对 `create-react-class` 的依赖。
